[package]
name = "cypat_scoring_engine"
version = "0.1.0"
authors = ["Teresa Maria Rivera"]
description = "A cyberpatriots scoring engine, or rather scoring library"
repository = "https://github.com/ComradeYellowCitrusFruit/cypat_v2"
keywords = ["cypat", "cyberpatriots"]
license = "GPL-3.0-only"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cypat"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
lazy_static = "1.4.0"
